### Remember to select the proper rest client environment

### 1. Get all saunas to have a general overview
GET {{host}}/sauna
Authorization: Basic {{token}}

### 3. Create new sauna (Assume that the created sauna gets `nextId` or should be replaced with a returned ID to continue with the test)
POST {{host}}/sauna
Authorization: Basic {{token}}
Content-Type: application/json

{
    "name": "Taloyhtiön sauna",
    "opened": "1996-08-08",
    "temperature": 92,
    "isPublic": false
}